sudo: false

language: node_js

node_js:
  - "4"
  - "6"

services:
  - redis

before_script:
  - redis-server --port 6378 --requirepass secret &
  - redis-server --port 6377 --unixsocket /tmp/redis.sock &
  - redis-sentinel test/sentinel.conf &
  - redis-sentinel test/sentinel2.conf &
  - sleep 2
